'use client'

import { useState, useEffect, useMemo } from 'react'
import { useRouter } from 'next/navigation'
import { Skeleton } from '@/components/ui/skeleton'
import { Empty, EmptyHeader, EmptyMedia, EmptyTitle, EmptyDescription } from '@/components/ui/empty'
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationLink,
  PaginationPrevious,
  PaginationNext,
} from '@/components/ui/pagination'
import { NoteListItem } from '@/components/notes/note-list-item'
import type { Note } from '@/types'

const PAGE_SIZE = 8

export default function NotesPage() {
  const [notes, setNotes] = useState<Note[]>([])
  const [loading, setLoading] = useState(true)
  const [page, setPage] = useState(1)
  const router = useRouter()

  useEffect(() => {
    fetch('/api/notes')
      .then(r => r.json())
      .then(setNotes)
      .finally(() => setLoading(false))
  }, [])

  const pages = Math.max(1, Math.ceil(notes.length / PAGE_SIZE))
  const visibleNotes = useMemo(
    () => notes.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE),
    [notes, page],
  )

  return (
    <div>
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-white">Notes</h1>
        <p className="text-zinc-500 text-sm mt-1">Markdown notes generated by the pipeline</p>
      </div>

      {loading ? (
        <div className="flex flex-col gap-2">
          {Array.from({ length: 4 }).map((_, i) => (
            <Skeleton key={i} className="h-[72px] w-full bg-zinc-900" />
          ))}
        </div>
      ) : notes.length === 0 ? (
        <Empty className="py-24">
          <EmptyHeader>
            <EmptyMedia variant="icon" className="bg-transparent text-4xl">📝</EmptyMedia>
            <EmptyTitle>No notes generated yet</EmptyTitle>
            <EmptyDescription>The full pipeline needs to run once.</EmptyDescription>
          </EmptyHeader>
        </Empty>
      ) : (
        <>
          <div className="flex flex-col gap-2">
            {visibleNotes.map(n => (
              <NoteListItem key={n.id} note={n} onClick={() => router.push(`/notes/${n.id}`)} />
            ))}
          </div>

          {pages > 1 && (
            <Pagination className="mt-6 justify-start">
              <PaginationContent>
                <PaginationItem>
                  <PaginationPrevious
                    onClick={() => setPage(p => Math.max(1, p - 1))}
                    aria-disabled={page === 1}
                    className={page === 1 ? 'opacity-40 pointer-events-none' : ''}
                  />
                </PaginationItem>
                {Array.from({ length: pages }).map((_, i) => (
                  <PaginationItem key={i}>
                    <PaginationLink isActive={page === i + 1} onClick={() => setPage(i + 1)}>
                      {i + 1}
                    </PaginationLink>
                  </PaginationItem>
                ))}
                <PaginationItem>
                  <PaginationNext
                    onClick={() => setPage(p => Math.min(pages, p + 1))}
                    aria-disabled={page === pages}
                    className={page === pages ? 'opacity-40 pointer-events-none' : ''}
                  />
                </PaginationItem>
              </PaginationContent>
            </Pagination>
          )}
        </>
      )}
    </div>
  )
}