'use client'

import { useState, useEffect, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { Input } from '@/components/ui/input'
import { Skeleton } from '@/components/ui/skeleton'
import { Empty, EmptyHeader, EmptyMedia, EmptyTitle, EmptyDescription } from '@/components/ui/empty'
import {
  Pagination, PaginationContent, PaginationItem,
  PaginationLink, PaginationPrevious, PaginationNext,
} from '@/components/ui/pagination'
import { NoteListItem } from '@/components/notes/note-list-item'
import { useDebounce } from '@/hooks/use-debouncer'
import type { Note } from '@/types'

const PAGE_SIZE = 12

export default function NotesPage() {
  const [notes, setNotes] = useState<Note[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [pages, setPages] = useState(1)
  const [search, setSearch] = useState('')
  const debouncedSearch = useDebounce(search, 300)
  const [loading, setLoading] = useState(true)
  const router = useRouter()

  const load = useCallback(async (p: number, q: string) => {
    setLoading(true)
    try {
      const res = await fetch(`/api/notes?page=${p}&limit=${PAGE_SIZE}&search=${encodeURIComponent(q)}`)
      const data = await res.json()
      setNotes(data.notes)
      setTotal(data.total)
      setPage(data.page)
      setPages(data.pages)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => { load(1, debouncedSearch) }, [debouncedSearch, load])

  const goPage = (p: number) => load(p, debouncedSearch)

  return (
    <div>
      <div className="flex justify-between items-start mb-6">
        <div>
          <h1 className="text-2xl font-bold text-white">Notes</h1>
          <p className="text-zinc-500 text-sm mt-1">
            {total > 0 ? `${total} note${total !== 1 ? 's' : ''}` : 'Markdown notes generated by the pipeline'}
          </p>
        </div>
      </div>

      <div className="mb-4">
        <Input
          value={search}
          onChange={e => { setSearch(e.target.value); setPage(1) }}
          placeholder="Search notes…"
          className="max-w-xs h-8 text-sm"
        />
      </div>

      {loading ? (
        <div className="flex flex-col gap-2">
          {Array.from({ length: 5 }).map((_, i) => (
            <Skeleton key={i} className="h-[72px] w-full bg-zinc-900" />
          ))}
        </div>
      ) : notes.length === 0 ? (
        <Empty className="py-24">
          <EmptyHeader>
            <EmptyMedia variant="icon" className="bg-transparent text-4xl">📝</EmptyMedia>
            <EmptyTitle>{search ? 'No notes match your search' : 'No notes generated yet'}</EmptyTitle>
            <EmptyDescription>
              {search ? 'Try a different search term.' : 'The full pipeline needs to run once.'}
            </EmptyDescription>
          </EmptyHeader>
        </Empty>
      ) : (
        <>
          <div className="flex flex-col gap-2">
            {notes.map(n => (
              <NoteListItem key={n.id} note={n} onClick={() => router.push(`/notes/${n.id}`)} />
            ))}
          </div>

          {pages > 1 && (
            <Pagination className="mt-6 justify-start">
              <PaginationContent>
                <PaginationItem>
                  <PaginationPrevious
                    onClick={() => goPage(Math.max(1, page - 1))}
                    className={page === 1 ? 'opacity-40 pointer-events-none' : ''}
                  />
                </PaginationItem>
                {Array.from({ length: pages }).map((_, i) => (
                  <PaginationItem key={i}>
                    <PaginationLink isActive={page === i + 1} onClick={() => goPage(i + 1)}>
                      {i + 1}
                    </PaginationLink>
                  </PaginationItem>
                ))}
                <PaginationItem>
                  <PaginationNext
                    onClick={() => goPage(Math.min(pages, page + 1))}
                    className={page === pages ? 'opacity-40 pointer-events-none' : ''}
                  />
                </PaginationItem>
              </PaginationContent>
            </Pagination>
          )}
        </>
      )}
    </div>
  )
}